# Generated by Django 4.0.5 on 2022-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_mobile_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(),
        ),
    ]
